# This config should be placed in following path:
#   $HOME/Library/Application Support/io.parity.ethereum/config.toml

[parity]
# Local Development Chain
chain = "dev"

[account]
# From: [,] you'll be able to send tranasactions without password.
unlock = ["0x009D478E4E9448B47f0b184AD6F05FaA0f8124C8", "0x00a329c0648769A73afAc7F9381E08FB43dBEA72"]
password = ["parity-pass-dev.txt"]





[mining]
# Gas limit will be raised at most by 1000000000 gas.
gas_cap = "987987987"
#tx_gas_limit = "987987987"